/**
 * Swagger Api Documentation for Bank Transaction application
 * swagger api documentation for Bank Transaction application
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * Contact: chamseddine1119@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AccountDto { 
    accountId?: number;
    person?: number;
    accountNum?: string;
    balancy?: number;
}
