/**
 * Swagger Api Documentation for Bank Transaction application
 * swagger api documentation for Bank Transaction application
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * Contact: chamseddine1119@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Adress } from './adress';
import { TypeLegalPerson } from './typeLegalPerson';


export interface LegalPersonDto { 
    id?: number;
    creationDate?: Date;
    updateDate?: Date;
    adress: Adress;
    phone?: string;
    name: string;
    matriculeFiscale: string;
    logo?: string;
    description?: string;
    email?: string;
    typeLegalPerson: TypeLegalPerson;
}
