/**
 * Swagger Api Documentation for Bank Transaction application
 * swagger api documentation for Bank Transaction application
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * Contact: chamseddine1119@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface RelationDto { 
    type?: RelationDto.TypeEnum;
    personTo?: number;
    personFrom?: number;
}
export namespace RelationDto {
    export type TypeEnum = 'INITIATOR' | 'VALIDATOR';
    export const TypeEnum = {
        INITIATOR: 'INITIATOR' as TypeEnum,
        VALIDATOR: 'VALIDATOR' as TypeEnum
    };
}
